services:
  - type: web
    name: hexigon-laravel-app
    env: docker
    plan: free
    repo: https://github.com/anpc33/order-system
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        fromDatabase:
            name: hexigon-order-system
            property: host
      - key: DB_PORT
        fromDatabase:
            name: hexigon-order-system
            property: port
      - key: DB_DATABASE
        fromDatabase:
            name: hexigon-order-system
            property: database
      - key: DB_USERNAME
        fromDatabase:
            name: hexigon-order-system
            property: user
      - key: DB_PASSWORD
        fromDatabase:
            name: hexigon-order-system
            property: password

  - type: worker
    name: queue-worker
    env: docker
    repo: https://github.com/anpc33/order-system
    dockerfilePath: ./Dockerfile
    startCommand: "php artisan queue:work"
    envVars:
      - fromGroup: hexigon-laravel-app
